apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestock-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codestock-frontend
  template:
    metadata:
      labels:
        app: codestock-frontend
    spec:
      containers:
      - name: frontend
        image: alejandromons/codestock-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: codestock-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: codestock-frontend
  ports:
    - port: 80
      targetPort: 80 