apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  labels:
    app: jenkins
  namespace: default
  
data:
  casc.yaml: |
    jenkins:
      systemMessage: "Jenkins listo para CodeStock!"
      numExecutors: 2
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: admin
              password: ${ADMIN_PASSWORD:-admin}
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default.svc.cluster.local"
            skipTlsVerify: true
            namespace: "default"
            jenkinsUrl: "http://jenkins-service.default.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-service.default.svc.cluster.local:50000"
            containerCapStr: "10"
            maxRequestsPerHostStr: "32"
            connectTimeout: 5
            readTimeout: 15
            templates:
              - name: "kaniko"
                label: "kaniko"
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:latest"
                    workingDir: "/home/jenkins/agent"
                    command: ""
                    args: ""
                  - name: "kaniko"
                    image: "gcr.io/kaniko-project/executor:v1.13.0"
                    command: "cat"
                    ttyEnabled: true
                volumes:
                  - secretVolume:
                      secretName: regcred 